### PR TITLE
Gr7j added

### PR DESCRIPTION
**Pull request by LynnSeo**
GR7J and GR8J added.

### CODE REVIEW

**Comment by floybix** [comment]
Hi, you have submitted a pull request to the "floybix/hydromad" repository, but that is outdated; the current repository is "josephguillaume/hydromad": https://github.com/josephguillaume/hydromad

Cheers
Felix

**Comment by floybix** [comment]
Also, it looks like you haven't actually made any commits yourself in this pull request. Might need to seek help from someone with git knowledge...

**Comment by LynnSeo** [comment]
Hi Felix

I hope you well in Hongkong? are you still in HK or somewhere?
I am Lynn and doing phd with Barry and Tony. Just want to thank you for
your excellent hydromad.
Unfortunately I may be the only one using hydromad in icam but my
colleagues in csiro love hydromad.
I know many people out there love hydromad.

Ah this is my first time using github. need to research on it.

Thank you,

Lynn

**Comment by floybix** [comment]
Good luck! Joseph's done all the work since he took over the project in 2011.

**Pull request closed without merging**
